### PR TITLE
TracingHandler should ignore active spans

### LINKED ISSUE #9: Bug: explicitly ignore active span
I was just reviewing the code -- and I think there may be a bug.
When you create a new Span in the `SpanHandler` I believe the code should be `ignoreActiveSpan` since by default the spans get registered with the `ActiveScopeManager` (defaults to ThreadLocal variable) which in an event loop model, will be no good.

Something akin to 

```
tracer.buildSpan(operationName)
                        .ignoreActiveSpan() //this is super important since we are not thread-per-request
                        .startManual()
```

### PR DESCRIPTION
**Pull request by fzakaria**
in an event loop model, ThreadLocal in ActiveSpanSource does not work
and can lead to tricky problems if not explicitly disabled.

- add explicit ignoring of any "active spans" while in the event loop
via TracingHandler
- addded unit test

fixes #9

### CODE REVIEW

**Comment by pavolloffay** [comment]
@fzakaria hi sorry I missed this PR. Could you please update the PR, I have merged something which breaks this.

**Comment by fzakaria** [comment]
@pavolloffay should be clean now.

**Comment by pavolloffay** [comment]
@fzakaria it seems it is not rebased against master/head as there are references to active span which has been removed.

**Comment by pavolloffay** [comment]
@fzakaria thanks

**Pull request merged**
